version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
  frontend:
    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - '8081:80'