version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317
      OTEL_SERVICE_NAME: com.andrewshawcare.smooks_api
      OTEL_RESOURCE_ATTRIBUTES: job=app
  frontend:
    image: nginx
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - '8081:80'