version: '3'
services:
  consumer:
    build: ./consumer
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317
      OTEL_PYTHON_LOG_CORRELATION: 'true'
      OTEL_SERVICE_NAME: consumer
      OTEL_RESOURCE_ATTRIBUTES: job=consumer
      LOGLEVEL: INFO