receivers:
  otlp:
    protocols:
      grpc:

processors:
  filter:
    logs:
      include:
        match_type: regexp
        bodies:
          - ^{
  transform:
    log_statements:
      - context: log
        statements:
          - merge_maps(attributes, ParseJSON(body), "upsert")
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: job
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: event, duration, errorType, errorMessages, messageId
  batch: {}

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      processors: [filter, transform, resource, attributes, batch]
      exporters: [loki]
