version: '3'
services:
  k6:
    build: ./performance
    environment:
      K6_VUS: 10
      K6_DURATION: 15m
    volumes:
      - ./performance-tests:/performance-tests:ro
    command: run /performance-tests/index.js