{
 "title": "Message pipeline",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "messageId", "label": "Message ID", "query": "ORDERS,INVRPT" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Count of events by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"app\"} | logfmt | event!=\"\" messageId=~\"${messageId}\" [${interval}])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Events every ${interval} by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (event) (rate({job=\"app\"} | logfmt | event!=\"\" [${interval}]))",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Mapping failure percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"app\"} | logfmt | event=\"MessageMappingFailed\"[${interval}])) / sum(count_over_time({job=\"app\"} | logfmt | event=~\"MessageMappingSucceeded|MessageMappingFailed\"[${interval}]))",
     "legendFormat": "MessageMappingFailed"
    }
   ]
  },
  {
   "title": "Mapping failure by error type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"app\"} | logfmt | errorType!=\"\" [${interval}])) by (errorType)",
     "legendFormat": "{{errorType}}"
    }
   ]
  }
 ]
}